### ISSUE TITLE
introduce the Nazi Olympics

### ISSUE THREAD

**Issue by Dabtion** [iteloo/bitesize-berlin#14]
introduction towards 1936 Olympics (basic information, as if you don't know anything about it and you're doing research and giving a really simple intro on it)

**Comment by ThomasTseng2005** [comment]
**Introduction:**
The Nazi Olympic is the 11th Summer Olympic hosted in 1936 in Berlin. Since the IOC wanted Germany to go back to the world community after the defeat in World War I, in 1931, Germany was assigned to host the 1936 Summer Olympic. After two years, Hitler became the chancellor and used the 1936 Summer Olympic as a way to spread the ‘Aryan propaganda’(showing people that Aryans are better), while trying to hide the racism against the Jews. To not make the rest of the world mad at them, the Nazis only allowed one Jewish fencer, Helene Maker, who won a silver medal for Germany.
