### ISSUE TITLE
What is the history of the Gate?

### ISSUE THREAD

**Issue by Ephemeral-Equilibrium** [iteloo/bitesize-berlin#22]
Make a timeline of the gate. fashfadshjafsd;lds

**Comment by Ephemeral-Equilibrium** [comment]
write at least 7 events 
choose the most important

**Comment by effervescence18** [comment]
1789 – 1791 the Brandenburg Gate is built as a
copy of the Propylaea in Athens;
originally called the Friedenstor
(Peace Gate) and is now the only
city gate in Berlin left from the 14
which once existed
1793 the quadriga is installed; the six
meter high statue is a copper
embossed team of four horses
carrying Victory, facing the city on
their return home
1806 Napoleon takes the quadriga with
the horses to Paris as booty. It is
brought back from Paris to Berlin
8 years later
1918 on November 9, the day of the
founding of the Weimar Republic
is celebrated at the Brandenburg
Gate
1933 on January 30, the group of former
front-line soldiers called the
“Steel Helmets” marches through
the Brandenburg Gate with torches
to celebrate the “gain of power”
by their party leader Adolf Hitler
1945 the Brandenburg Gate is in ruins
as a result of fighting in Berlin near
the end of World War II
1953 on June 17, workers revolt in East
Berlin; the angry workers take the
Communist flag down from the
Brandenburg Gate and then
march with the German flag to the
western side of the city
1961 the Brandenburg Gate is tightly
sealed; the gate and quadriga are
not allowed to be approached by
visitors since the area of the “AntiFascist
Protective Wall” is off-limits
for defense reasons
1963 U.S. President J.F. Kennedy visits
Berlin in June and says his famous
words, “Ich bin ein Berliner!”
1985 the Brandenburg Gate is blocked
by the border wall; sightseeing
platforms in West Berlin allow visitors
to take a look into the east
1987 the east Berliners can only see the
Brandenburg Gate from a distance;
U.S. President Ronald Reagan
stands in front of the gate and
appeals to USSR leader Mikhail
Gorbachev in a noted speech to
“Tear down this wall.”
1989 on October 19, no one believes
the wall will one day disappear
1989 on November 9, travel restrictions
for citizens of East Germany are
lifted; a wild celebration occurs
next to and on top of the Brandenburg
Gate; the wall falls
1999/2000 thousands of people celebrate
New Year 2000 at the Brandenburg
Gate

**Comment by effervescence18** [comment]
![screen shot 2018-03-22 at 10 33 40 am](https://user-images.githubusercontent.com/37429576/37747937-8a93b4f4-2dbc-11e8-96f6-64a01b041bf5.png)

**Comment by Glamorous-Potatoes** [comment]
1789 – 1791 the Brandenburg Gate is built as a
copy of the Propylaea in Athens;
originally called the Friedenstor
(Peace Gate) and is now the only
city gate in Berlin left from the 14
which once existed
------------------------------------------------------------------------------------------------------
1793 the quadriga is installed; the six
meter high statue is a copper
embossed team of four horses
carrying Victory, facing the city on
their return home
------------------------------------------------------------------------------------------------------
1806 Napoleon takes the quadriga with
the horses to Paris as booty. It is
brought back from Paris to Berlin
8 years later
------------------------------------------------------------------------------------------------------
1918 on November 9, the day of the
founding of the Weimar Republic
is celebrated at the Brandenburg
Gate
------------------------------------------------------------------------------------------------------
1933 on January 30, the group of former
front-line soldiers called the
“Steel Helmets” marches through
the Brandenburg Gate with torches
to celebrate the “gain of power”
by their party leader Adolf Hitler
------------------------------------------------------------------------------------------------------
1945 the Brandenburg Gate is in ruins
as a result of fighting in Berlin near
the end of World War II
------------------------------------------------------------------------------------------------------
1953 on June 17, workers revolt in East
Berlin; the angry workers take the
Communist flag down from the
Brandenburg Gate and then
march with the German flag to the
western side of the city
------------------------------------------------------------------------------------------------------
1961 the Brandenburg Gate is tightly
sealed; the gate and quadriga are
not allowed to be approached by
visitors since the area of the “AntiFascist
Protective Wall” is off-limits
for defense reasons
------------------------------------------------------------------------------------------------------
1963 U.S. President J.F. Kennedy visits
Berlin in June and says his famous
words, “Ich bin ein Berliner!”
1985 the Brandenburg Gate is blocked
by the border wall; sightseeing
platforms in West Berlin allow visitors
to take a look into the east
------------------------------------------------------------------------------------------------------
1987 the east Berliners can only see the
Brandenburg Gate from a distance;
U.S. President Ronald Reagan
stands in front of the gate and
appeals to USSR leader Mikhail
Gorbachev in a noted speech to
“Tear down this wall.”
------------------------------------------------------------------------------------------------------
1989 on October 19, no one believes
the wall will one day disappear
------------------------------------------------------------------------------------------------------
1989 on November 9, travel restrictions
for citizens of East Germany are
lifted; a wild celebration occurs
next to and on top of the Brandenburg
Gate; the wall falls
------------------------------------------------------------------------------------------------------
1999/2000 thousands of people celebrate
New Year 2000 at the Brandenburg
Gate
