### ISSUE TITLE
Find Jewish Owner Information

### ISSUE THREAD

**Issue by nini92828** [iteloo/bitesize-berlin#3]
Find more information of the historical background, especially its Jewish owner
- Why he build it
- Was he special in the Jewish Community
- What happened to him

**Comment by effervescence18** [comment]
(1) **Why he built it?**  
Wanted "upper and highest consumer desires of the Wilhelmine elite."
(2) **Was he special in the Jewish Community?**
Wealthiest wholesale merchants in Germany
(3) **What happened to him?**
Forced to sell it to German owners during the Nazis rose to power named Hermann Tietz. 
Later given to a privately held Thai firm named Central Group.
Attacked by anti-semitism, the file created with the resentment towards Jewish merchants tend to devalue donations
Awarded "Commercial Council" in 1910 by Bavarian King

**Comment by ThomasTseng2005** [comment]
**KaDeWe Important People and Company:**

   Adolf Jandorf: German founder of KaDeWe

   Hermann Tietz: Jewish owner of KadeWe, his family tried to expand KaDeWe during the Third Reich.   Since there were Nazi laws against the Jews, at that time, “Hertie” became the name for “KaDeWe”

   Central Group: Current owner of KaDeWe
